### ISSUE TITLE
Option to use the Facebook Share dialog in addition to the Feed dialog.

### ISSUE THREAD

**Issue by madsgodvinjensen** [avdeev/vanilla-sharing#14]
When sharing from a page, you would need to use the Share dialog. Can we add that option in this library? I am happy to help with a PR if we can agree on an implementation.

We can add as a parameter/flag on the existing facebook dialog function. But that would mean some nasty internals in the function, as the parameters the two dialogs use are different.

Another option is to add a fbShare function (and maybe renaming fb -> fbFeed) to make it more explicit.

Documentation on the dialog:

https://developers.facebook.com/docs/sharing/reference/share-dialog

**Comment by avdeev** [comment]
Hi, @madsgodvinjensen! Thanks for the issue.

You can create PR with "add a fbShare function (and maybe renaming fb -> fbFeed)". I like this option.

**Comment by madsgodvinjensen** [comment]
Cool. I have a PR up: https://github.com/avdeev/vanilla-sharing/pull/15

**Comment by avdeev** [comment]
@madsgodvinjensen Added in the release v3.0.0
