### ISSUE TITLE
Deprecated FB Feed Dialog parameters

### ISSUE THREAD

**Issue by mkhazov** [avdeev/vanilla-sharing#16]
https://developers.facebook.com/docs/sharing/reference/feed-dialog

Deprecated Parameters, still being used in this library:
`picture `
`name`
`description`

**Comment by avdeev** [comment]
Resolved in https://github.com/avdeev/vanilla-sharing/commit/1c014abfa87cf0349120e0a00788438ced077f7f

**Comment by vhs1092** [comment]
Since those parameters are deprecated, how do I send the image? the post is sharing only with title and description, without image
