### ISSUE TITLE
Add Redit / Tumblr / Others?

### ISSUE THREAD

**Issue by nightsurge** [avdeev/vanilla-sharing#22]
Is there any plan to integrate these and other popular sharing sites?

Is the library easy to extend to add custom ones for these? Reddit, at the very least, is critical for my usage.

**Comment by avdeev** [comment]
@nightsurge Welcome for PR

**Comment by nightsurge** [comment]
PR submitted @avdeev  :)

**Comment by avdeev** [comment]
@nightsurge Reddit added in v5.1.0, thanks!

What about the others? :)

**Comment by avdeev** [comment]
Tumblr added in #30 

@nightsurge You can try it! :)
