### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [avdeev/vanilla-sharing#25]
Hello, I just finished this logo for your project. Tell me if you liked it and I'll send the files on a PR.

![vanillasharing](https://user-images.githubusercontent.com/35619342/38597140-cc6c2e94-3d23-11e8-8a17-962f864d8103.png)

**Comment by avdeev** [comment]
@michaelizer Awesome! PR welcome!

**Comment by michaelizer** [comment]
Done, [#26](https://github.com/avdeev/vanilla-sharing/pull/26). It was my pleasure

**Comment by avdeev** [comment]
Merged.

@michaelizer Looks good! Thank you!
