### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by exoclick-florin-tudor** [avdeev/vanilla-sharing#27]
It would be great to have the @types package defined to use this library with typescript.

**Comment by avdeev** [comment]
Sounds good!
PR welcome :)

**Comment by avdeev** [comment]
@exoclick-florin-tudor 
I read types readme. Will do it soon

**Comment by avdeev** [comment]
@exoclick-florin-tudor Can you review my PR?

**Comment by avdeev** [comment]
Closed via #31
