### ISSUE TITLE
Subject line in email sharing

### ISSUE THREAD

**Issue by iancwinter** [avdeev/vanilla-sharing#34]
Is it possible to add a subject line to the email sharing?

Not sure how to go about it within your code, but the final structure of your link is:

mailto:?body=

…and this could be enhanced using:

mailto:?subject=supplied_subject_here&body=

…with subject being one of the option parameters.

**Comment by avdeev** [comment]
@iancwinter I've done it in v5.6.0
You can try.

Close issue plz if everything is ok.

**Comment by iancwinter** [comment]
Modification tested and working fine, thanks.
